# Generated by Django 4.0.2 on 2022-02-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbuy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
