# Generated by Django 4.0.2 on 2022-02-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbuy', '0002_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_id',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
